#!/usr/bin/env python3
"""Regenerate gates/INDEX.md from the gate configs.

The index is generated rather than hand-written so it cannot drift from the
thresholds actually in force. Run after changing any gate config:

    python3 gates/build_index.py
"""
from __future__ import annotations

import json
from pathlib import Path

GATES_DIR = Path(__file__).resolve().parent
INDEX = GATES_DIR / "INDEX.md"

CATEGORY = {
    "model-effort-route": "Cost",
    "tool-worth-it": "Cost",
    "redundant-tool-call": "Cost",
    "subagent-spawn": "Cost",
    "context-read-budget": "Cost",
    "stop-vs-continue": "Performance",
    "retry-worth-it": "Performance",
    "parallel-fanout": "Performance",
    "plan-vs-act": "Quality",
    "skill-selection": "Quality",
    "verification-sufficient": "Quality",
    "response-quality": "Quality",
    "destructive-action": "Safety",
    "secret-exposure": "Safety",
    "external-write": "Safety",
}

ORDER = ["Safety", "Cost", "Performance", "Quality"]


def gate_dirs() -> list[Path]:
    return sorted(d for d in GATES_DIR.iterdir() if d.is_dir() and d.name != "common")


def first_paragraph(spec: Path) -> str:
    """Pull the gate's stated purpose out of its SPEC's `## Purpose` section."""
    if not spec.is_file():
        return ""
    lines = spec.read_text(encoding="utf-8").splitlines()
    for idx, line in enumerate(lines):
        if line.strip().lower().startswith("## purpose"):
            for candidate in lines[idx + 1:]:
                candidate = candidate.strip()
                if candidate.startswith("#"):
                    break
                if candidate:
                    # Keep the table cell readable.
                    return candidate.replace("|", "\\|").rstrip(".")
            break
    return ""


def format_thresholds(thresholds: dict) -> str:
    if not thresholds:
        return "—"
    parts = []
    for key, value in sorted(thresholds.items()):
        if isinstance(value, list):
            value = ", ".join(str(v) for v in value)
        parts.append(f"`{key}`={value}")
    return "<br>".join(parts)


def main() -> int:
    rows_by_category: dict[str, list[str]] = {name: [] for name in ORDER}

    for gate in gate_dirs():
        config = json.loads((gate / "config.json").read_text(encoding="utf-8"))
        slug = gate.name
        category = CATEGORY.get(slug, "Uncategorised")
        fail_mode = config.get("fail_mode", "?")
        default = config.get("default_on_error") or {}
        questions = list((config.get("questions") or {}).keys())
        rows_by_category.setdefault(category, []).append(
            f"| [`{slug}`]({slug}/SPEC.md) "
            f"| {first_paragraph(gate / 'SPEC.md')} "
            f"| {format_thresholds(config.get('thresholds') or {})} "
            f"| **{fail_mode}** → `{default.get('action', '?')}` "
            f"| {', '.join(f'`{q}`' for q in questions)} |"
        )

    lines = [
        "# Gate index",
        "",
        "> Generated by `gates/build_index.py`. Do not edit by hand — "
        "regenerate it so the thresholds here always match the configs in force.",
        "",
        "Every gate ships `SPEC.md`, `config.json`, `gate.py`, `example_state.json`, "
        "a recorded fixture and a dry artifact, and runs offline with no API key.",
        "",
        "**Fail mode** is what the gate does when Jev cannot be reached or answers "
        "unusably. `closed` refuses to proceed; `open` allows. Every safety gate is "
        "`closed`, and their hard rules resolve locally *before* Jev is called at all, "
        "so an outage cannot unblock them.",
        "",
    ]

    for category in ORDER:
        rows = rows_by_category.get(category) or []
        if not rows:
            continue
        lines += [
            f"## {category}",
            "",
            "| Gate | Purpose | Thresholds | Fail mode | Jev questions |",
            "|---|---|---|---|---|",
            *sorted(rows),
            "",
        ]

    total = sum(len(v) for v in rows_by_category.values())
    lines += [
        "---",
        "",
        f"{total} gates. Run them all offline:",
        "",
        "```bash",
        "for d in gates/*/; do s=$(basename $d); [ \"$s\" = common ] && continue; \\",
        "  JEV_MODE=fixture python3 -B \"gates/$s/gate.py\"; done",
        "```",
        "",
    ]

    INDEX.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {INDEX} ({total} gates)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
